name: Checks

on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembleRelease

  merge:
    runs-on: ubuntu-latest
    needs: [ test-build ]
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
